version: '3.9'

services:
  backend:
    build:
      context: ./globalCharBackEnd
      dockerfile: Dockerfile
    image: globalchat-backend
    ports:
      - "8000:8000"
    volumes:
      - ./globalCharBackEnd:/app
    env_file:
      - ./globalCharBackEnd/.env

  frontend:
    build:
      context: ./globalChat
      dockerfile: Dockerfile
    image: globalchat-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
