version: "3.9"

services:
  backend:
    build: ./globalCharBackEnd
    ports:
      - "8000:8000"
    volumes:
      - ./globalCharBackEnd:/app
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build: ./globalChat
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
